"""update or db

Revision ID: 1087f812a916
Revises: 
Create Date: 2024-05-05 20:26:38.784248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1087f812a916'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consulta',
    sa.Column('id_consulta', sa.Integer(), nullable=False),
    sa.Column('crm', sa.Text(), nullable=True),
    sa.Column('id_especialidade', sa.Integer(), nullable=True),
    sa.Column('id_paciente', sa.Text(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('hora_inicio', sa.Integer(), nullable=True),
    sa.Column('hora_fim', sa.Integer(), nullable=True),
    sa.Column('pagou', sa.Text(), nullable=True),
    sa.Column('valor_pago', sa.Text(), nullable=True),
    sa.Column('forma_pagamento', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crm'], ['medico.crm'], ),
    sa.ForeignKeyConstraint(['id_especialidade'], ['exerc_esp.id'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_consulta')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consulta')
    # ### end Alembic commands ###
