"""update or db

Revision ID: 3db05f50657f
Revises: 
Create Date: 2024-05-05 12:15:05.064513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3db05f50657f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AGENDA',
    sa.Column('id_agenda', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Text(), nullable=True),
    sa.Column('hora_inicio', sa.Text(), nullable=True),
    sa.Column('hora_fim', sa.Text(), nullable=True),
    sa.Column('crm', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_agenda')
    )
    op.create_table('CONSULTA',
    sa.Column('id_consulta', sa.Integer(), nullable=False),
    sa.Column('crm', sa.Text(), nullable=True),
    sa.Column('id_especialidade', sa.Text(), nullable=True),
    sa.Column('id_paciente', sa.Text(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('hora_fim', sa.DateTime(), nullable=False),
    sa.Column('pagou', sa.Text(), nullable=True),
    sa.Column('valor_pago', sa.Text(), nullable=True),
    sa.Column('forma_pagamento', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_consulta')
    )
    op.create_table('DIAGNOSTICO',
    sa.Column('id_diagnostico', sa.Integer(), nullable=False),
    sa.Column('tratamento_recomendado', sa.Text(), nullable=True),
    sa.Column('remedios_receitados', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id_consulta', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_diagnostico')
    )
    op.create_table('DOENCA',
    sa.Column('id_doenca', sa.Integer(), nullable=False),
    sa.Column('nome_doenca', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_doenca')
    )
    op.create_table('ESPECIALIDADE',
    sa.Column('indice', sa.Integer(), nullable=False),
    sa.Column('nome_especialidade', sa.Text(), nullable=True),
    sa.Column('id_especialidade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('indice')
    )
    op.create_table('EXERC_ESP',
    sa.Column('crm', sa.Integer(), nullable=False),
    sa.Column('id_especialidade', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('crm')
    )
    op.create_table('MEDICO',
    sa.Column('crm', sa.Text(), nullable=False),
    sa.Column('nome_medico', sa.Text(), nullable=True),
    sa.Column('telefone_medico', sa.Text(), nullable=True),
    sa.Column('porcentual', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('crm')
    )
    op.create_table('PACIENTE',
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.Text(), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('nome_paciente', sa.Text(), nullable=True),
    sa.Column('telefone_paciente', sa.Text(), nullable=True),
    sa.Column('sexo', sa.Text(), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_paciente')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('PACIENTE')
    op.drop_table('MEDICO')
    op.drop_table('EXERC_ESP')
    op.drop_table('ESPECIALIDADE')
    op.drop_table('DOENCA')
    op.drop_table('DIAGNOSTICO')
    op.drop_table('CONSULTA')
    op.drop_table('AGENDA')
    # ### end Alembic commands ###
