"""update or db

Revision ID: 48a4f50e6726
Revises: 
Create Date: 2024-05-05 22:13:56.687758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a4f50e6726'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consulta',
    sa.Column('id_consulta', sa.Integer(), nullable=False),
    sa.Column('crm', sa.Text(), nullable=True),
    sa.Column('id_especialidade', sa.Text(), nullable=True),
    sa.Column('id_paciente', sa.Text(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('hora_inicio', sa.Integer(), nullable=True),
    sa.Column('hora_fim', sa.Integer(), nullable=True),
    sa.Column('pagou', sa.Text(), nullable=True),
    sa.Column('valor_pago', sa.Text(), nullable=True),
    sa.Column('forma_pagamento', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crm'], ['medico.crm'], ),
    sa.ForeignKeyConstraint(['id_especialidade'], ['especialidade.id_especialidade'], ),
    sa.ForeignKeyConstraint(['id_paciente'], ['paciente.id_paciente'], ),
    sa.PrimaryKeyConstraint('id_consulta')
    )
    with op.batch_alter_table('exerc_esp', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exerc_esp', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.drop_table('consulta')
    # ### end Alembic commands ###
