"""update or db

Revision ID: c7a76669b588
Revises: f00dfab6a521
Create Date: 2024-05-05 14:51:33.801820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a76669b588'
down_revision = 'f00dfab6a521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exerc_esp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_especialidade', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'especialidade', ['id_especialidade'], ['id_especialidade'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exerc_esp', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_especialidade')

    # ### end Alembic commands ###
