"""update or db

Revision ID: f00dfab6a521
Revises: 
Create Date: 2024-05-05 14:50:39.778034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f00dfab6a521'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consulta',
    sa.Column('id_consulta', sa.Integer(), nullable=False),
    sa.Column('crm', sa.Text(), nullable=True),
    sa.Column('id_especialidade', sa.Text(), nullable=True),
    sa.Column('id_paciente', sa.Text(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('hora_fim', sa.DateTime(), nullable=False),
    sa.Column('pagou', sa.Text(), nullable=True),
    sa.Column('valor_pago', sa.Text(), nullable=True),
    sa.Column('forma_pagamento', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_consulta')
    )
    op.create_table('diagnostico',
    sa.Column('id_diagnostico', sa.Text(), nullable=False),
    sa.Column('tratamento_recomendado', sa.Text(), nullable=True),
    sa.Column('remedios_receitados', sa.Text(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id_consulta', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_diagnostico')
    )
    op.create_table('doenca',
    sa.Column('id_doenca', sa.Text(), nullable=False),
    sa.Column('nome_doenca', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_doenca')
    )
    op.create_table('especialidade',
    sa.Column('nome_especialidade', sa.Text(), nullable=True),
    sa.Column('id_especialidade', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id_especialidade')
    )
    op.create_table('medico',
    sa.Column('crm', sa.Text(), nullable=False),
    sa.Column('nome_medico', sa.Text(), nullable=True),
    sa.Column('telefone_medico', sa.Text(), nullable=True),
    sa.Column('porcentual', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('crm')
    )
    op.create_table('paciente',
    sa.Column('id_paciente', sa.Text(), nullable=False),
    sa.Column('cpf', sa.Text(), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('nome_paciente', sa.Text(), nullable=True),
    sa.Column('telefone_paciente', sa.Text(), nullable=True),
    sa.Column('sexo', sa.Text(), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_paciente')
    )
    op.create_table('agenda',
    sa.Column('id_agenda', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Text(), nullable=True),
    sa.Column('hora_inicio', sa.Text(), nullable=True),
    sa.Column('hora_fim', sa.Text(), nullable=True),
    sa.Column('crm', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crm'], ['medico.crm'], ),
    sa.PrimaryKeyConstraint('id_agenda')
    )
    op.create_table('diagnostica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_diagnostico', sa.Text(), nullable=True),
    sa.Column('id_doenca', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_diagnostico'], ['diagnostico.id_diagnostico'], ),
    sa.ForeignKeyConstraint(['id_doenca'], ['doenca.id_doenca'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exerc_esp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['crm'], ['medico.crm'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('PACIENTE')
    op.drop_table('AGENDA')
    op.drop_table('ESPECIALIDADE')
    op.drop_table('DOENCA')
    op.drop_table('MEDICO')
    op.drop_table('CONSULTA')
    op.drop_table('DIAGNOSTICO')
    op.drop_table('EXERC_ESP')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EXERC_ESP',
    sa.Column('crm', sa.INTEGER(), server_default=sa.text('nextval(\'"EXERC_ESP_crm_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('id_especialidade', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('crm', name='EXERC_ESP_pkey')
    )
    op.create_table('DIAGNOSTICO',
    sa.Column('id_diagnostico', sa.INTEGER(), server_default=sa.text('nextval(\'"DIAGNOSTICO_id_diagnostico_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('tratamento_recomendado', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('remedios_receitados', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_consulta', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_diagnostico', name='DIAGNOSTICO_pkey')
    )
    op.create_table('CONSULTA',
    sa.Column('id_consulta', sa.INTEGER(), server_default=sa.text('nextval(\'"CONSULTA_id_consulta_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('crm', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_especialidade', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_paciente', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('hora_inicio', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('hora_fim', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('pagou', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('valor_pago', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('forma_pagamento', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_consulta', name='CONSULTA_pkey')
    )
    op.create_table('MEDICO',
    sa.Column('crm', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('nome_medico', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('telefone_medico', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('porcentual', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('crm', name='MEDICO_pkey')
    )
    op.create_table('DOENCA',
    sa.Column('id_doenca', sa.INTEGER(), server_default=sa.text('nextval(\'"DOENCA_id_doenca_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('nome_doenca', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_doenca', name='DOENCA_pkey')
    )
    op.create_table('ESPECIALIDADE',
    sa.Column('indice', sa.INTEGER(), server_default=sa.text('nextval(\'"ESPECIALIDADE_indice_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('nome_especialidade', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id_especialidade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('indice', name='ESPECIALIDADE_pkey')
    )
    op.create_table('AGENDA',
    sa.Column('id_agenda', sa.INTEGER(), server_default=sa.text('nextval(\'"AGENDA_id_agenda_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('dia_semana', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hora_inicio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hora_fim', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('crm', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_agenda', name='AGENDA_pkey')
    )
    op.create_table('PACIENTE',
    sa.Column('id_paciente', sa.INTEGER(), server_default=sa.text('nextval(\'"PACIENTE_id_paciente_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('endereco', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nome_paciente', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('telefone_paciente', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sexo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_paciente', name='PACIENTE_pkey')
    )
    op.drop_table('exerc_esp')
    op.drop_table('diagnostica')
    op.drop_table('agenda')
    op.drop_table('paciente')
    op.drop_table('medico')
    op.drop_table('especialidade')
    op.drop_table('doenca')
    op.drop_table('diagnostico')
    op.drop_table('consulta')
    # ### end Alembic commands ###
